########################################################################################################################
# https://docs.sonarsource.com/sonarqube-cloud/analyzing-source-code/automatic-analysis
#
# You can refine the configuration of your analyses by adding a .sonarcloud.properties file to your repository’s default
# branch. Note that this is different from the sonar-project.properties file used for CI-based analysis.
########################################################################################################################

# Path to sources
sonar.sources=./src/
# sonar.exclusions=
# sonar.inclusions=

# Path to tests
sonar.tests=./test/
# sonar.test.exclusions=
# sonar.test.inclusions=

# Source encoding
# sonar.sourceEncoding=

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=

# Python version (for python projects only)
# sonar.python.version=

# C++ standard version (for C++ projects only)
# If not specified, it defaults to the latest supported standard
# sonar.cfamily.reportingCppStandardOverride=c++98|c++11|c++14|c++17|c++20