name: Node.js CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Download artifact smws codes
      uses: dsaltares/fetch-gh-release-asset@aa2ab1243d6e0d5b405b973c89fa4d06a2d0fff7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: "data.json"
        repo: "elliottback/SMWS_Codes"
        target: "./data.json"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install stuff
      run: npm ci

    - name: build
      run: npm run ci

    - name: Install chrome
      run: npx @puppeteer/browsers install chrome@stable

    - name: Start Xvfb and Test
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99
        npm test

    - name: Archive  artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dist
        if-no-files-found: error
        path: |
          dist/*.png