name: Node.js CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Download artifact smws codes
      uses: dsaltares/fetch-gh-release-asset@1.1.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: "data.json"
        repo: "elliottback/SMWS_Codes"
        target: "./data.json"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install stuff
      run: npm ci
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

    - name: build
      run: npm run ci

    - name: Run headful puppeteer tests
      uses: elliottback/puppeteer-headful@22.18.0
      with:
        args: npm test

    - name: Archive  artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dist
        if-no-files-found: error
        path: |
          dist/*.png