name: Node.js CI

on: [pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4

    - name: Download artifact smws codes
      uses: dsaltares/fetch-gh-release-asset@1.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: "data.json"
        repo: "elliottback/SMWS_Codes"
        target: "./data.json"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install stuff
      run: npm ci
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

    - name: build
      run: npm run ci

    - name: Run headful puppeteer tests
      uses: mujo-code/puppeteer-headful@18.9.0
      with:
        args: npm test

    - name: Archive  artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        if-no-files-found: error
        path: |
          dist/*.png